In [1]:
# load the raw dataset
import numpy as np
import pandas as pd
from pandas import DataFrame

rawdf = pd.read_csv("unc.edu_PANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv", sep="\t", index_col=0)
rawdf.head()

,TCGA-OR-A5J1-01A-11R-A29S-07,TCGA-OR-A5J2-01A-11R-A29S-07,TCGA-OR-A5J3-01A-11R-A29S-07,TCGA-OR-A5J5-01A-11R-A29S-07,TCGA-OR-A5J6-01A-31R-A29S-07,TCGA-OR-A5J7-01A-11R-A29S-07,TCGA-OR-A5J8-01A-11R-A29S-07,TCGA-OR-A5J9-01A-11R-A29S-07,TCGA-OR-A5JA-01A-11R-A29S-07,TCGA-OR-A5JB-01A-11R-A29S-07,...,TCGA-VQ-AA6A-01A-11R-A414-31,TCGA-VQ-AA6B-01A-11R-A414-31,TCGA-VQ-AA6D-01A-11R-A414-31,TCGA-VQ-AA6F-01A-31R-A414-31,TCGA-VQ-AA6G-01A-11R-A414-31,TCGA-VQ-AA6I-01A-11R-A414-31,TCGA-VQ-AA6J-01A-11R-A414-31,TCGA-VQ-AA6K-01A-11R-A414-31,TCGA-ZA-A8F6-01A-23R-A36D-31,TCGA-ZQ-A9CR-01A-11R-A39E-31
0.0gene_id,,,,,,,,,,,,,,,,,,,,,
?|100130426,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.3189,0.0000,0.0000,0.0000,0.0000,0.2466,0.4134,0.0000,0.5668
?|100133144,3.2661,2.6815,1.7301,0.0000,0.0000,1.1673,1.4422,0.0000,4.4556,7.1293,...,26.1744,28.1937,32.4153,18.6091,33.7625,35.0189,27.6770,28.6855,29.3939,19.8016
?|100134869,3.9385,8.9948,6.5650,1.5492,4.4709,6.0529,2.2876,1.3599,5.0581,0.0000,...,14.3662,16.5156,21.5482,17.2753,20.2653,30.1605,19.2494,21.1378,15.4703,8.5379
?|10357,149.1350,81.0777,86.4879,53.9117,66.9063,103.5060,94.9316,78.1955,69.2389,155.7090,...,11.5541,10.0447,15.9546,21.9117,8.4115,21.6463,35.6665,11.5371,22.0386,29.3701
?|10431,2034.1000,1304.9300,1054.6600,2350.8900,1257.9900,1866.4300,995.0270,1762.1200,1213.5300,2005.5700,...,357.7860,780.6260,903.2380,1033.0300,733.7430,519.9930,709.6430,702.4730,561.9840,1874.0200

In [2]:
# transpose raw dataset so row is patient samples and column is list of genes
processeddf = rawdf.transpose()
processeddf.head()

0.0gene_id,?|100130426,?|100133144,?|100134869,?|10357,?|10431,?|136542,?|155060,?|26823,?|280660,?|317712,...,ZXDA|7789,ZXDB|158586,ZXDC|79364,ZYG11A|440590,ZYG11B|79699,ZYX|7791,ZZEF1|23140,ZZZ3|26009,psiTPTE22|387590,tAKR|389932
TCGA-OR-A5J1-01A-11R-A29S-07,0.0,3.2661,3.9385,149.1350,2034.10,0.0,274.255,1.4409,0.0,0.0,...,20.6532,351.585,1050.910,0.4803,648.415,1841.020,1157.540,596.062,715.658,0.9606
TCGA-OR-A5J2-01A-11R-A29S-07,0.0,2.6815,8.9948,81.0777,1304.93,0.0,199.302,0.0000,0.0,0.0,...,57.1735,279.023,2979.870,31.4052,1166.020,3059.990,1895.990,801.637,581.801,0.4026
TCGA-OR-A5J3-01A-11R-A29S-07,0.0,1.7301,6.5650,86.4879,1054.66,0.0,348.393,0.5925,0.0,0.0,...,39.6978,495.334,914.827,0.5925,806.399,2655.610,1482.450,437.269,126.796,0.0000
TCGA-OR-A5J5-01A-11R-A29S-07,0.0,0.0000,1.5492,53.9117,2350.89,0.0,439.194,0.7746,0.0,0.0,...,17.8156,206.042,890.782,11.6189,553.834,2367.930,1140.200,512.781,855.151,0.0000
TCGA-OR-A5J6-01A-31R-A29S-07,0.0,0.0000,4.4709,66.9063,1257.99,0.0,149.215,0.0000,0.0,0.0,...,12.8537,117.919,894.730,7.8240,795.812,708.071,796.371,475.587,288.370,0.0000

In [6]:
# check to see if there is any feature (i.e. column) has all zero values so we will delete them
removedAllZeroColdf = processeddf.loc[:, (processeddf != 0).any(axis=0)]
removedAllZeroColdf.shape

(10471, 20319)

In [8]:
# data scaling
# method 1 : standardization
from sklearn.preprocessing import StandardScaler

stdscaler = StandardScaler()
stdscalerfit = stdscaler.fit_transform(removedAllZeroColdf)

stddf = DataFrame(stdscalerfit)
stddf.head()

,0,1,2,3,4,5,6,7,8,9,...,20309,20310,20311,20312,20313,20314,20315,20316,20317,20318
0,-0.160942,-0.617169,-0.576054,0.381991,2.670834,-0.031973,0.157343,0.840137,-0.110518,-0.018862,...,-1.119447,-0.275935,-0.226144,-0.323150,-0.613014,-0.890816,-0.239301,-0.498587,1.137707,-0.120793
1,-0.160942,-0.660038,-0.245485,-0.530733,0.869174,-0.031973,-0.178775,-0.612835,-0.110518,-0.018862,...,0.030730,-0.592270,3.777421,-0.148785,0.441277,-0.537709,0.802185,0.105872,0.858771,-0.139824
2,-0.160942,-0.729806,-0.404340,-0.458176,0.250798,-0.031973,0.489805,-0.015371,-0.110518,-0.018862,...,-0.519653,0.350741,-0.508585,-0.322517,-0.291222,-0.654849,0.218941,-0.965491,-0.089382,-0.153554
3,-0.160942,-0.856677,-0.732261,-0.895059,3.453570,-0.031973,0.896991,0.168255,-0.110518,-0.018862,...,-1.208814,-0.910432,-0.558491,-0.260347,-0.805662,-0.738183,-0.263757,-0.743461,1.428387,-0.153554
4,-0.160942,-0.856677,-0.541247,-0.720787,0.753193,-0.031973,-0.403383,-0.612835,-0.110518,-0.018862,...,-1.365085,-1.294606,-0.550297,-0.281743,-0.312786,-1.219005,-0.748683,-0.852823,0.247311,-0.153554

In [9]:
# data scaling
# method 2 : min-max norm
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
min_max_scalerfit = min_max_scaler.fit_transform(removedAllZeroColdf)

minmaxdf = DataFrame(min_max_scalerfit)
minmaxdf.head()

,0,1,2,3,4,5,6,7,8,9,...,20309,20310,20311,20312,20313,20314,20315,20316,20317,20318
0,0.0,0.014150,0.005582,0.133253,0.359331,0.0,0.056625,0.049655,0.0,0.0,...,0.060077,0.078297,0.147137,0.000053,0.027287,0.034613,0.120181,0.061289,0.058052,0.001154
1,0.0,0.011617,0.012749,0.072443,0.214986,0.0,0.040957,0.000000,0.0,0.0,...,0.166310,0.062108,0.487358,0.003470,0.051955,0.059411,0.206637,0.086754,0.047194,0.000483
2,0.0,0.007495,0.009305,0.077277,0.165443,0.0,0.072123,0.020418,0.0,0.0,...,0.115475,0.110367,0.123136,0.000065,0.034816,0.051184,0.158220,0.041620,0.010285,0.000000
3,0.0,0.000000,0.002196,0.048170,0.422042,0.0,0.091104,0.026694,0.0,0.0,...,0.051823,0.045826,0.118895,0.001284,0.022779,0.045332,0.118150,0.050974,0.069367,0.000000
4,0.0,0.000000,0.006337,0.059781,0.205694,0.0,0.030487,0.000000,0.0,0.0,...,0.037390,0.026166,0.119591,0.000864,0.034311,0.011564,0.077896,0.046366,0.023392,0.000000