In [1]:
# load the raw dataset
import numpy as np
import pandas as pd
from pandas import DataFrame

rawdf = pd.read_csv("unc.edu_PANCAN_IlluminaHiSeq_RNASeqV2.geneExp.tsv", sep="\t", index_col=0)
rawdf.head()

,TCGA-OR-A5J1-01A-11R-A29S-07,TCGA-OR-A5J2-01A-11R-A29S-07,TCGA-OR-A5J3-01A-11R-A29S-07,TCGA-OR-A5J5-01A-11R-A29S-07,TCGA-OR-A5J6-01A-31R-A29S-07,TCGA-OR-A5J7-01A-11R-A29S-07,TCGA-OR-A5J8-01A-11R-A29S-07,TCGA-OR-A5J9-01A-11R-A29S-07,TCGA-OR-A5JA-01A-11R-A29S-07,TCGA-OR-A5JB-01A-11R-A29S-07,...,TCGA-VQ-AA6A-01A-11R-A414-31,TCGA-VQ-AA6B-01A-11R-A414-31,TCGA-VQ-AA6D-01A-11R-A414-31,TCGA-VQ-AA6F-01A-31R-A414-31,TCGA-VQ-AA6G-01A-11R-A414-31,TCGA-VQ-AA6I-01A-11R-A414-31,TCGA-VQ-AA6J-01A-11R-A414-31,TCGA-VQ-AA6K-01A-11R-A414-31,TCGA-ZA-A8F6-01A-23R-A36D-31,TCGA-ZQ-A9CR-01A-11R-A39E-31
0.0gene_id,,,,,,,,,,,,,,,,,,,,,
?|100130426,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.3189,0.0000,0.0000,0.0000,0.0000,0.2466,0.4134,0.0000,0.5668
?|100133144,3.2661,2.6815,1.7301,0.0000,0.0000,1.1673,1.4422,0.0000,4.4556,7.1293,...,26.1744,28.1937,32.4153,18.6091,33.7625,35.0189,27.6770,28.6855,29.3939,19.8016
?|100134869,3.9385,8.9948,6.5650,1.5492,4.4709,6.0529,2.2876,1.3599,5.0581,0.0000,...,14.3662,16.5156,21.5482,17.2753,20.2653,30.1605,19.2494,21.1378,15.4703,8.5379
?|10357,149.1350,81.0777,86.4879,53.9117,66.9063,103.5060,94.9316,78.1955,69.2389,155.7090,...,11.5541,10.0447,15.9546,21.9117,8.4115,21.6463,35.6665,11.5371,22.0386,29.3701
?|10431,2034.1000,1304.9300,1054.6600,2350.8900,1257.9900,1866.4300,995.0270,1762.1200,1213.5300,2005.5700,...,357.7860,780.6260,903.2380,1033.0300,733.7430,519.9930,709.6430,702.4730,561.9840,1874.0200

In [2]:
# transpose raw dataset so row is patient samples and column is list of genes
processeddf = rawdf.transpose()
processeddf.head()

0.0gene_id,?|100130426,?|100133144,?|100134869,?|10357,?|10431,?|136542,?|155060,?|26823,?|280660,?|317712,...,ZXDA|7789,ZXDB|158586,ZXDC|79364,ZYG11A|440590,ZYG11B|79699,ZYX|7791,ZZEF1|23140,ZZZ3|26009,psiTPTE22|387590,tAKR|389932
TCGA-OR-A5J1-01A-11R-A29S-07,0.0,3.2661,3.9385,149.1350,2034.10,0.0,274.255,1.4409,0.0,0.0,...,20.6532,351.585,1050.910,0.4803,648.415,1841.020,1157.540,596.062,715.658,0.9606
TCGA-OR-A5J2-01A-11R-A29S-07,0.0,2.6815,8.9948,81.0777,1304.93,0.0,199.302,0.0000,0.0,0.0,...,57.1735,279.023,2979.870,31.4052,1166.020,3059.990,1895.990,801.637,581.801,0.4026
TCGA-OR-A5J3-01A-11R-A29S-07,0.0,1.7301,6.5650,86.4879,1054.66,0.0,348.393,0.5925,0.0,0.0,...,39.6978,495.334,914.827,0.5925,806.399,2655.610,1482.450,437.269,126.796,0.0000
TCGA-OR-A5J5-01A-11R-A29S-07,0.0,0.0000,1.5492,53.9117,2350.89,0.0,439.194,0.7746,0.0,0.0,...,17.8156,206.042,890.782,11.6189,553.834,2367.930,1140.200,512.781,855.151,0.0000
TCGA-OR-A5J6-01A-31R-A29S-07,0.0,0.0000,4.4709,66.9063,1257.99,0.0,149.215,0.0000,0.0,0.0,...,12.8537,117.919,894.730,7.8240,795.812,708.071,796.371,475.587,288.370,0.0000

In [3]:
# check to see if there is any missing values
processeddf.isnull().any().any()
# answer is no

False

In [4]:
# check to see if any duplicate rows/samples
processeddf.index.get_duplicates()

[]

In [5]:
# check to see if any duplicate columns/features
processeddf.transpose().index.get_duplicates()

[]

In [6]:
# check to see if there is any feature (i.e. column) has all zero values so we will delete them
removedAllZeroColdf = processeddf.loc[:, (processeddf != 0).any(axis=0)]
removedAllZeroColdf.shape

(10471, 20319)

In [7]:
# calculate how many features/columns has all zeros and we have removed them
removedFeatures = processeddf.shape[1] - removedAllZeroColdf.shape[1]
removedFeatures
# 212 features are removed from the data set

212

In [8]:
# list out the removed 212 features and manually confirm that they are right
original = DataFrame(processeddf.columns)
original.columns = ['genelist']
removed = DataFrame(removedAllZeroColdf.columns)
removed.columns = ['genelist']

original[~original.genelist.isin(removed.genelist)].head()

                  genelist
7661  HBII-52-24|100036563
7662  HBII-52-27|100036564
7663  HBII-52-28|100036565
7664  HBII-52-45|100036566
7665  HBII-52-46|100036567

In [9]:
# manually confirm the first example gene #7661 (HBII-52-24|100036563) is all empty so it is removed

count = 0
potentiallyAllZeroColumn = processeddf['HBII-52-24|100036563']
for i in range(10471):
    if(potentiallyAllZeroColumn[i] == 0.0):
        count = count+1
        
print(count)

10471